version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 10s
      retries: 5

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3001
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DATABASE=ngcash_transactions
      - HOSTNAME=db
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5

  database:
    image: postgres:14.3-alpine
    container_name: database
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 30s 
    cap_add:
      - SYS_NICE